# -*- coding: utf-8 -*-
"""Multi-Agent System for Instagram Content Creation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KvcBencvg_vx1IFzU1_drgt8NAndVaXg
"""

# !pip install crewai crewai-tools langchain ollama

"""# Instagram Content Package Generator

This notebook utilizes a CrewAI framework to generate content for Instagram posts about a specified topic. It includes agents for research, writing, reviewing, and image generation.

## Functionality

The notebook performs the following steps:

1. **Setup:** Imports necessary libraries and configures the LLM (OpenAI in this case).
2. **Image Generation Tool:** Defines a tool using `diffusers` and the "segmind/SSD-1B" model to generate images based on text prompts and saves them locally.
3. **Agent Definition:** Defines four agents:
    - **Researcher:** Gathers information on the topic.
    - **Writer:** Creates short-form and long-form Instagram captions.
    - **Reviewer:** Polishes and finalizes the captions and hashtags.
    - **Image Generator:** Creates image prompts and uses the image generation tool.
4. **Task Definition:** Defines the tasks for each agent.
5. **Crew Creation:** Assembles the agents and tasks into a sequential crew.
6. **Execution:** Runs the crew with a given topic, generating research, captions, hashtags, image prompts, and images.

## How to Use

1. **Install Dependencies:** Run the pip install commands in the first few cells if you haven't already.
2. **Set up API Key:** Ensure your OpenAI API key is stored in Colab's user data with the key name '4.1' and the `OPENAI_API_KEY` environment variable is set (or the `api_key` parameter in the `ChatOpenAI` initialization is used).
3. **Define Topic:** Modify the `topic` variable in the "Execute Crew" section to your desired topic.
4. **Run All Cells:** Execute all the code cells in the notebook.
5. **View Output:** The final output will include the polished captions, hashtags, and the file paths of the generated images. The images themselves will be saved locally in the same directory as the notebook.

## Output Structure

The final output of the crew execution will contain the results from each task, including:

- A summary of the research.
- The short-form and long-form Instagram captions.
- The finalized list of hashtags.
- The image prompts used and the file paths of the generated images.

The generated images are saved locally as `.png` files with a timestamp in the filename.
"""

# !pip install langchain_openai

from crewai import Agent, LLM, Crew, Process, Task, TaskOutput, CrewOutput
from crewai.tools import tool
from langchain_openai import ChatOpenAI

import warnings
warnings.filterwarnings('ignore')

"""# LLM"""

import os
from google.colab import userdata
from langchain_openai import ChatOpenAI # Import ChatOpenAI

# Retrieve the API key from Colab's user data
key = userdata.get('4.1')

# Set the OPENAI_API_KEY environment variable
# os.environ["OPENAI_API_KEY"] = key

# Initialize the ChatOpenAI model
openai_llm = LLM(
    api_key=key,
    base_url="https://models.github.ai/inference",
    model="openai/gpt-4.1",
)

# openai_llm.invoke("hello")

import torch
from diffusers import StableDiffusionXLPipeline
# from IPython.display import display # Remove display
from crewai.tools import tool
from PIL import Image # Import Image
import os
import time # Import time for timestamp in filename

# Initialize the pipeline once
pipe = StableDiffusionXLPipeline.from_pretrained(
    "segmind/SSD-1B",
    torch_dtype=torch.float16,
    use_safetensors=True,
    variant="fp16"
).to("cuda")

@tool("generate_image_with_segmind")
def generate_image_with_segmind(prompt: str) -> str: # Change return type hint to str
    """
    Generates an image with Segmind (SSD-1B model) based on the given prompt using diffusers,
    saves the image to a local file, and returns the file path.
    """
    print(f"Generating image with prompt: {prompt}") # Debugging print

    image = pipe(
        prompt=prompt,
        negative_prompt="ugly, darkness, blurry, poor quality",
        width=1500 - (1500 % 8),
        height=750 - (750 % 8),
        guidance_scale=7,
        num_inference_steps=28
    ).images[0]

    # Save the image to a local file
    timestamp = int(time.time())
    filename = f"generated_image_{timestamp}.png"
    image_path = os.path.join(".", filename) # Save in the current directory
    image.save(image_path)
    print(f"Image saved to: {image_path}") # Debugging print

    # display(image) # Remove display

    return image_path # Return the image file path as a string

"""# Research Agent"""

research_agent = Agent(
			role="Researcher",
			goal="Conduct in-depth research and gather information about {topic}.",
			backstory=
            "You're working on planning a blog article "
            "about the topic: {topic}."
            "You collect information that helps the "
            "audience learn something "
            "and make informed decisions. "
            "Your work is the basis for "
            "the Content Writer to write an article on this topic.",
			allow_delegation=False,
			llm=openai_llm,
			verbose=True
		)

"""# Writer Agent"""

writer_agent = Agent(
            role="Writer",
            goal="Write compelling Instagram captions (short-form + long-form version) based on research about {topic}, including relevant hashtags and a call to action.",
            backstory=
            "You are a creative content writer specializing in "
            "compelling Instagram captions. "
            "You take the research provided by the Research Agent "
            "and craft engaging short-form and long-form captions "
            "optimized for Instagram, including relevant hashtags "
            "and a call to action. You work closely with the Reviewer Agent "
            "to ensure the captions are polished and effective.",
            allow_delegation=False,
            llm=openai_llm,
            verbose=True,
            memory=True
        )

"""# Reviewer Agent"""

reviewer_Agent = Agent(
            role="Reviewer",
            goal="Review and refine Instagram captions for {topic}.",
            backstory=
            "You are an editor who receives Instagram captions "
            "from the Content Writer. "
            "Your goal is to review the captions to ensure they are "
            "polished, grammatically correct, and optimized for clarity, "
            "engagement, and tone. You also verify that they align with the "
            "research and project objectives.",
            allow_delegation=False,
            llm=openai_llm,
            verbose=True,
            memory=True
        )

"""# Image Generator Agent"""

image_agent = Agent(
            role="Designer",
            goal="Generate 2–3 strong text-to-image prompts for {topic}, "
            "and always call the generate_image_with_segmind tool with at least one prompt "
            "to produce and display a real image using diffusers.",
            backstory=
            "You specialize in creating image prompts and generating visuals "
            "with an image generation tool using diffusers. Your job is to ensure the images align with the "
            "Instagram caption content and are displayed in the notebook."
            ,
            allow_delegation=False,
            llm=openai_llm,
            verbose=True,
            memory=True,
            tools=[generate_image_with_segmind]
        )

"""# Define Tasks"""

research_task = Task(
    description=(
        "Conduct in-depth research on the topic: {topic}."
        "Identify key points, interesting facts, and potential angles "
        "that would be engaging for an Instagram audience."
        "Compile your findings into a concise summary."
    ),
    expected_output='A concise summary of key points and interesting facts about {topic} for an Instagram audience.',
    agent=research_agent,
)

writer_task = Task(
    description=(
        "Using the research summary provided, write two versions of an Instagram caption for {topic}: "
        "1. A short-form caption (under 150 characters including hashtags) "
        "2. A long-form caption (up to 2200 characters including hashtags) "
        "Both captions should be compelling, include a relevant call to action, and suggest relevant hashtags."
    ),
    expected_output='Two Instagram captions (short-form and long-form) for {topic}, including a call to action and relevant hashtags.',
    agent=writer_agent,
)

reviewer_task = Task(
    description=(
        "Review the short-form and long-form Instagram captions for {topic} provided by the writer."
        "Ensure they are grammatically correct, clear, engaging, and maintain an appropriate tone."
        "Refine the captions for maximum impact and verify the relevance of the suggested hashtags."
        "Provide the final, polished versions of both captions and the finalized list of hashtags."
    ),
    expected_output='The final, polished short-form and long-form Instagram captions for {topic} and a finalized list of relevant hashtags.',
    agent=reviewer_Agent,
)

image_prompt_task = Task(
    description=(
        "Based on the topic {topic} and the content of the Instagram captions "
        "(both short and long form), generate 2 to 3 detailed and creative "
        "text-to-image prompts. For EACH generated prompt, use "
        "the generate_image_with_segmind tool to produce and display a real image."
    ),
    expected_output=(
        "2 to 3 detailed text-to-image prompts for {topic} based on the Instagram caption content, "
        "and the file paths to 2 to 3 generated images that were saved locally using generate_image_with_segmind."
    ),
    agent=image_agent,
)

"""# Create Crew"""

content_crew = Crew(
    agents=[research_agent, writer_agent, reviewer_Agent, image_agent],
    tasks=[research_task, writer_task, reviewer_task, image_prompt_task],
    process=Process.sequential,
    verbose=True,
)

# openai_llm.invoke("hello")

"""# Execute Crew"""

from IPython.display import Markdown
# Define the topic
topic = "The Future of AI in Healthcare"

# Kickoff the crew process
result = content_crew.kickoff(inputs={'topic': topic})
# Print the results
print("## Here is the Instagram Content Package ##")
print(result)

# display(Markdown(str(result))) # Convert result to string

# task_output: TaskOutput = result.tasks_output[0]
# crew_output: CrewOutput = result.output

# Inspect the raw output of the reviewer task to understand its structure
print(result.tasks_output[2].raw)

from IPython.display import display, Markdown
from PIL import Image # Import Image (although not strictly needed for printing text)

# Access the raw string output using the 'raw' attribute
reviewer_output_string = result.tasks_output[2].raw  # Assuming reviewer_task is the 3rd task (index 2)
image_task_output = result.tasks_output[3] # Access the full task output for the image task (index 3)
image_output_string = image_task_output.raw # Get the raw string output

# Initialize variables to hold extracted content
short_caption = "Short-form caption not found."
long_caption = "Long-form caption not found."
hashtags = "Hashtags not found."

# Robustly extract captions and hashtags
long_caption_split = reviewer_output_string.split('Long-form Instagram Caption')
if len(long_caption_split) > 1:
    short_caption_part = long_caption_split[0]
    # Extract short caption - assuming it's everything before "Long-form Instagram Caption"
    short_caption = short_caption_part.replace('Short-form Instagram Caption (Polished):', '').strip() # Updated marker based on reviewer output

    hashtags_split = long_caption_split[1].split('Finalized List of Hashtags:')
    if len(hashtags_split) > 1:
        # Extract long caption - everything between "Long-form Instagram Caption" and "Finalized List of Relevant Hashtags:"
        long_caption = hashtags_split[0].replace('(Polished):', '').strip() # Updated marker
        # Extract hashtags - everything after "Finalized List of Relevant Hashtags:"
        hashtags = hashtags_split[1].strip()
    else:
        # If hashtags section is not found after long caption
        long_caption = long_caption_split[1].replace('(Polished):', '').strip() # Updated marker
        hashtags = "Hashtags section marker not found."
else:
    # If "Long-form Instagram Caption" marker is not found at all
    short_caption = reviewer_output_string.strip()
    long_caption = "Long-form caption marker not found."
    hashtags = "Hashtags marker not found."


# Combine the text outputs into a single string
instagram_package_text = f"""
## Complete Instagram Post Package for "{topic}"

### Instagram Captions

**Short-form Caption:**
{short_caption}

**Long-form Caption:**
{long_caption}

### Relevant Hashtags
{hashtags}

### Generated Images and Prompts

{image_output_string}
"""

# Print the combined text package
print(instagram_package_text)

# Acknowledge that images were generated and saved to local files
print("\n## Generated Images (Saved Locally) ##")
print("Images were generated and saved to local files during the execution of the image generation task.")

# Note: Code to display images from task_output.result was removed as it caused errors and images are displayed by the tool.
# The image_task_output.raw string contains the text output from the image agent, which should include filenames.

"""## Summary:

### Data Analysis Key Findings

*   The `generate_image_with_segmind` function was successfully modified to save generated images to local files named `generated_image_[timestamp].png` and return the file path string.
*   The direct display of images using `display(image)` was removed from the image generation function.
*   The final output generation logic was updated to indicate that images are saved locally rather than displayed.
*   The `expected_output` description for the `image_prompt_task` was updated to reflect that file paths to locally saved images will be part of the output.

### Insights or Next Steps

*   Ensure that the directory where images are saved has appropriate write permissions.
*   Consider adding error handling to the image saving process in case of file writing issues.

"""